App/Entities/Award.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Entities
{
    public class Award : EntityBase
    {
        public Award()
        {
        }

        public Award(string title, string description)
        {
            Title = title;
            Description = description;
        }

        public string Title { get; set; }
        public string Description { get; set; }
        public virtual Image Image { get; set; }
        public int? ImageId { get; set; }
    }
}

App/Entities/EntityBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Entities
{
    public abstract class EntityBase
    {
        public virtual int Id { get; set; }
    }
}

App/Entities/Image.cs
using System;

namespace App.Entities
{
    public class Image : EntityBase
    {
        public string FileName { get; set; }
        public string Path { get; set; }

        public string Url => System.IO.Path.Combine(this.Path, FileName);
    }
}

App/Entities/User.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Entities
{
    public class User : EntityBase
    {
        public User()
        {
        }

        public User(string firstName, string lastName, DateTime birthDate)
        {
            FirstName = firstName;
            LastName = lastName;
            BirthDate = birthDate;
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
        public virtual Image Image { get; set; }
        public int? ImageId { get; set; }
    }
}

App/Models/AwardDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Models
{
    public class AwardDto
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}

App/Models/UserDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Models
{
    public class UserDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string ImageUrl { get; set; }
    }
}

App/Controllers/AwardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Entities;
using App.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class AwardsController : Controller
    {
        private IAwardRepository repository;

        public AwardsController(IAwardRepository repository)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
        }

        public IActionResult Index()
        {
            return View(repository.GetAll());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var award = repository.GetById(id);
            if (award == null)
            {
                return RedirectToAction("AwardNotFound");
            }

            return View(award);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Award award)
        {
            repository.Add(award);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var award = repository.GetById(id);
            if (award == null)
            {
                return RedirectToAction("AwardNotFound");
            }

            repository.Delete(award);
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Award awardUpdate)
        {
            var award = repository.GetById(awardUpdate.Id);

            if (award == null )
            {
                return RedirectToAction("AwardNotFound");
            }

            award.Title = awardUpdate.Title;
            award.Description = awardUpdate.Description;

            repository.Update(award);

            return RedirectToAction("Index");
        }

        public IActionResult AwardNotFound()
        {
            Response.StatusCode = 404;
            return View();
        }
    }
}

App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

App/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Entities;
using App.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserRepository repository;
        private readonly IMapper mapper;

        public UsersController(IUserRepository repository, IMapper mapper)
        {
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
        }

        public IActionResult Index()
        {
            return View(mapper.ToUserDtos(repository.GetAll()));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var user = repository.GetById(id);
            if (user == null)
            {
                return RedirectToAction("UserNotFound");
            }

            return View("Edit", user);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var user = repository.GetById(id);
            if (user == null)
            {
                return RedirectToAction("UserNotFound");
            }

            repository.Delete(user);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            repository.Add(user);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(User userUpdate)
        {
            var user = repository.GetById(userUpdate.Id);
            if (user == null)
            {
                return RedirectToAction("UserNotFound");
            }
            user.FirstName = userUpdate.FirstName;
            user.LastName = userUpdate.LastName;
            user.BirthDate = userUpdate.BirthDate;

            repository.Update(user);

            return RedirectToAction("Index");
        }

        public IActionResult UserNotFound()
        {
            Response.StatusCode = 404;
            return View();
        }

    }
}

App/Views/Awards/AwardNotFound.cshtml
<h2>Error:</h2>
<p>The requested award was not found.</p>

App/Views/Awards/Create.cshtml
@model Award

<h2>Create award:</h2>
<hr />
<form asp-action="Create" asp-controller="Awards" asp-antiforgery="true" method="post">
    <input asp-for="Id" hidden />
    <div>
        <label asp-for="Title"></label>
        <input asp-for="Title" />
    </div>
    <div>
        <label asp-for="Description"></label>
        <input asp-for="Description" />
    </div>
    <hr />
    <div>
        <input type="submit" value="Save" />
        <a asp-action="Index" asp-controller="Awards">Cancel</a>
    </div>
</form>

App/Views/Awards/Edit.cshtml
@model Award
<h2>Edit award:</h2>
<hr />
<form asp-action="Edit" asp-controller="Awards" asp-antiforgery="true" method="post">
    <input asp-for="Id" hidden />
    <div>
        <label asp-for="Title"></label>
        <input asp-for="Title" />
    </div>
    <div>
        <label asp-for="Description"></label>
        <input asp-for="Description" />
    </div>
    <hr />
    <div>
        <input type="submit" value="Save" />
        <input type="submit" value="Delete" asp-action="Delete" asp-controller="Awards" asp-route-id=@Model.Id />
        <a asp-action="Index" asp-controller="Awards">Cancel</a>
    </div>
</form>

App/Views/Awards/Index.cshtml
@model IEnumerable<Award>

<h3>Awards:</h3>
<ol>
    @foreach (var item in Model)
    {
        <li>
            @item.Title - @item.Description  <a asp-action="Edit" asp-controller="Awards" asp-route-id="@item.Id">Edit</a>
        </li>
    }
</ol>
<a asp-action="Create" asp-controller="Awards">New award</a>
    

App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h2>Hello ASP.NET World!</h2>
</div>

App/Views/Home/NotFound.cshtml
<h2>Error:</h2>
<p>The requested resource was not found on this server.</p>

App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserAwardApp</title>
</head>
<body>
    <header>
        <a asp-action="Index" asp-controller="Home">Home</a>
        <a asp-action="Index" asp-controller="Users">Users</a>
        <a asp-action="Index" asp-controller="Awards">Awards</a>
    </header>
    <main>
        @RenderBody()
    </main>
</body>
</html>

App/Views/Users/Create.cshtml
@model User

<h2>Create user:</h2>
<hr />
<form asp-action="Create" asp-controller="Users" asp-antiforgery="true" method="post">
    <input asp-for="Id" hidden />
    <div>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" />
    </div>
    <div>
        <label asp-for="LastName"></label>
        <input asp-for="LastName" />
    </div>
    <div>
        <label asp-for="BirthDate"></label>
        <input asp-for="BirthDate" />
    </div>
    <hr />
    <div>
        <input type="submit" value="Save" />
        <a asp-action="Index" asp-controller="Users">Cancel</a>
    </div>
</form>

App/Views/Users/Edit.cshtml
@model User
    <h2>Edit user:</h2>
    <hr />
    <form asp-action="Edit" asp-controller="Users" asp-antiforgery="true" method="post">
        <input asp-for="Id" hidden/>
        <div>
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" />
        </div>
        <div>
            <label asp-for="LastName"></label>
            <input asp-for="LastName" />
        </div>
        <div>
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" />
        </div>
        <hr />
        <div>
            <input type="submit" value="Save" />
            <input type="submit" value="Delete" asp-action="Delete" asp-controller="Users" asp-route-id=@Model.Id/>
            <a asp-action="Index" asp-controller="Users">Cancel</a>
        </div>
    </form>

App/Views/Users/Index.cshtml
@model IEnumerable<UserDto>

<h3>Users:</h3>
<ol>
@{
    foreach (var item in Model)
    {
    <li>
        @item.Name: @item.Age <a asp-action="Edit" asp-controller="Users" asp-route-id="@item.Id">Edit</a>
    </li>
    } 
}
</ol>
<a asp-action="Create" asp-controller="Users">New user</a>

App/Views/Users/UserNotFound.cshtml
<h2>Error:</h2>
<p>The requested user was not found.</p>